entrada = input('Digite algo: ')

print(type(entrada))
print('É alfanumérico ? {}'.format(entrada.isalnum()))
print('É alfabético ? {}'.format(entrada.isalpha()))
print('Está em ascii ? {}'.format(entrada.isascii()))
print('É decimal ? {}'.format(entrada.isdecimal()))
print('São digitos ? {}'.format(entrada.isdigit()))
print('É um identificador válido ? {}'.format(entrada.isidentifier()))
print('Está em minúscula ? {}'.format(entrada.islower()))
print('É um número ? {}'.format(entrada.isnumeric()))
print('É printável ? {}'.format(entrada.isprintable()))
print('É um espaço ? {}'.format(entrada.isspace()))
print('É um título ? {}'.format(entrada.istitle()))
print('Está em maiúscula ? {}'.format(entrada.isupper()))